-- Eidolons table for collectible entities
CREATE TABLE IF NOT EXISTS eidolons (
	id SERIAL PRIMARY KEY,
	code VARCHAR(12) UNIQUE, -- human-friendly ID like 'ED01' generated by trigger
	name VARCHAR(100) NOT NULL,
	rarity VARCHAR(10) NOT NULL CHECK (rarity IN ('C', 'UC', 'R', 'SR', 'SSR')),
	element VARCHAR(20) NOT NULL,
	description TEXT,
	lore TEXT,
	base_attack INTEGER DEFAULT 100,
	base_defense INTEGER DEFAULT 100,
	base_speed INTEGER DEFAULT 100,
	skill_name VARCHAR(100),
	skill_description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Trigger/function to populate `code` for eidolons (prefix 'ED')
CREATE OR REPLACE FUNCTION set_eidolon_code() RETURNS trigger AS $$
BEGIN
	UPDATE eidolons SET code = 'ED' || LPAD(NEW.id::text, 2, '0') WHERE id = NEW.id;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER eidolons_set_code AFTER INSERT ON eidolons
FOR EACH ROW EXECUTE FUNCTION set_eidolon_code();
